/* SPDX-License-Identifier: MIT */
#define _GNU_SOURCE
#include "generator.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

static char *sanitize(const char *s) {
    char *out = strdup(s);
    for (char *p = out; *p; ++p) {
        if (*p == '/' || *p == '@' || *p == ':') *p = '_';
    }
    return out;
}

static int dir_exists(const char *path) {
    struct stat st;
    return stat(path, &st) == 0 && S_ISDIR(st.st_mode);
}

int bazel_generate(resolved_t *list, size_t n) {
    char cmd[512];
    snprintf(cmd, sizeof(cmd), "mkdir -p .cpm");
    if (system(cmd) != 0) return -1;

    FILE *fp = fopen(".cpm/cpm.bzl", "w");
    if (!fp) return -1;

    fprintf(fp, "# Auto-generated by cpm\n");
    fprintf(fp, "CPM_INCLUDE_PATHS = [\n");

    if (n > 0) {
        for (size_t i = 0; i < n; ++i) {
            char *clean_module = sanitize(list[i].module);
            char *clean_version = sanitize(list[i].version);

            char include_path[512];
            snprintf(include_path, sizeof(include_path),
                    ".cpm/vendor/%s@%s/include", clean_module, clean_version);

            if (dir_exists(include_path)) {
                fprintf(fp, "    \".cpm/vendor/%s@%s/include\",\n",
                        clean_module, clean_version);
            } else {
                fprintf(fp, "    \".cpm/vendor/%s@%s\",\n",
                        clean_module, clean_version);
            }

            free(clean_module);
            free(clean_version);
        }
    }
    
    fprintf(fp, "]\n");
    fclose(fp);
    return 0;
}
