/* SPDX-License-Identifier: TODO */
#define _GNU_SOURCE
#include "generator.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

static char *sanitize(const char *s) {
    char *out = strdup(s);
    for (char *p = out; *p; ++p) {
        if (*p == '/' || *p == '@' || *p == ':') *p = '_';
    }
    return out;
}

static int dir_exists(const char *path) {
    struct stat st;
    return stat(path, &st) == 0 && S_ISDIR(st.st_mode);
}

int make_generate(resolved_t *list, size_t n, int compile_flags) {
    char cmd[512];
    snprintf(cmd, sizeof(cmd), "mkdir -p .cpm");
    if (system(cmd) != 0) return -1;

    FILE *fp = fopen(".cpm/cpm.mk", "w");
    if (!fp) return -1;

    // Optionally generate compile_flags.txt for clangd.
    // Only written when compile_flags = true in cmod.toml.
    FILE *cf = NULL;
    if (compile_flags) {
        cf = fopen("compile_flags.txt", "w");
        if (cf) {
            if (dir_exists("include")) fprintf(cf, "-Iinclude\n");
            if (dir_exists("src"))     fprintf(cf, "-Isrc\n");
        }
    }

    fprintf(fp, "# Auto-generated by cpm\n");
    fprintf(fp, "CPM_VENDOR_PATH := .cpm/vendor\n");

    if (n > 0) {
        fprintf(fp, "# CPM include flags\n");
        for (size_t i = 0; i < n; ++i) {
            char *clean_module = sanitize(list[i].module);
            char *clean_version = sanitize(list[i].version);

            char include_path[512];
            snprintf(include_path, sizeof(include_path),
                    ".cpm/vendor/%s@%s/include", clean_module, clean_version);

            if (dir_exists(include_path)) {
                fprintf(fp, "CFLAGS += -isystem $(CPM_VENDOR_PATH)/%s@%s/include\n",
                        clean_module, clean_version);
                if (cf) {
                    fprintf(cf, "-isystem\n");
                    fprintf(cf, ".cpm/vendor/%s@%s/include\n", clean_module, clean_version);
                }
            } else {
                fprintf(fp, "CFLAGS += -isystem $(CPM_VENDOR_PATH)/%s@%s\n",
                        clean_module, clean_version);
                if (cf) {
                    fprintf(cf, "-isystem\n");
                    fprintf(cf, ".cpm/vendor/%s@%s\n", clean_module, clean_version);
                }
            }

            free(clean_module);
            free(clean_version);
        }

        fprintf(fp, "# CPM link flags (if static libs are present)\n");
        for (size_t i = 0; i < n; ++i) {
            char *clean_module = sanitize(list[i].module);
            char *clean_version = sanitize(list[i].version);

            char lib_path[512];
            snprintf(lib_path, sizeof(lib_path),
                    ".cpm/vendor/%s@%s/lib", clean_module, clean_version);

            if (dir_exists(lib_path)) {
                fprintf(fp, "LDFLAGS += -L$(CPM_VENDOR_PATH)/%s@%s/lib\n",
                        clean_module, clean_version);
            }

            free(clean_module);
            free(clean_version);
        }
    }

    fclose(fp);
    if (cf) fclose(cf);
    return 0;
}